services:
  postgresdb:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_HOST
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - postgresdb
    environment:
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_HOST
      DB_PORT: 5432
    ports:
      - "8080:8080"
    restart: always
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  pgdata:
